post_install() {
    sed -e "s|ID=manjaro|ID=sonar|" \
        -e "s|Manjaro Linux|Sonar Linux|g" \
        -e "s|http://www.manjaro.org/|http://www.sonargnulinux.com/|g" \
        -i usr/lib/os-release
}

post_remove() {
    sed -e "s|ID=sonar|ID=manjaro|" \
        -e "s|Sonar Linux|Manjaro Linux|g" \
        -e "s|http://www.sonargnulinux.com/|http://www.manjaro.org/|g" \
        -i usr/lib/os-release
}
