#!/bin/sh

msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
	local mesg=$1; shift
	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

post_install() {
	if [ -f /etc/pacman-mirrors.conf.pacsave ]; then
		msg "Your current config has been restored."
		msg "A new configuration is saved as /etc/pacman-mirrors.conf.$(date +%Y%m%d)."
		msg "Please verify any changes made to the configuration."
		mv /etc/pacman-mirrors.conf /etc/pacman-mirrors.conf.$(date +%y%m%d)
		mv /etc/pacman-mirrors.conf.pacsave /etc/pacman-mirrors.conf
	fi
	if [ -f /etc/pacman.d/mirrorlist ]; then
		/usr/bin/pacman-mirrors --no-mirrorlist
	else
		/usr/bin/pacman-mirrors -yf5
        fi
	message
}


post_upgrade() {
	/usr/bin/pacman-mirrors --no-mirrorlist
	message
}

message() {
	echo ""
	echo "hint: use \`pacman-mirrors\` to generate and update your pacman mirrorlist."
}
